SELECT 
    ED.YEAR, 
    (ED.MAX_SIZE - ED1.SIZE_OF_COLONY) AS YEAR_DEV, 
    ED1.ID
FROM 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS ED
JOIN 
    ECOLI_DATA AS ED1 
ON 
    YEAR(ED1.DIFFERENTIATION_DATE) = ED.YEAR
ORDER BY ED.YEAR, YEAR_DEV;