SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO AS B ON A.FISH_TYPE = B.FISH_TYPE
JOIN (
    SELECT FISH_NAME, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS FI
    JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
    GROUP BY FISH_NAME
) AS C ON B.FISH_NAME = C.FISH_NAME AND A.LENGTH = C.MAX_LENGTH
ORDER BY A.ID;
