-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY,PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자","국","김치","식용유")
    GROUP BY CATEGORY
)
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC

# 식용유 : 8950, 김치 : 19000, 국 : 2900 과자 : 1950